#ifndef __HUD_OBJECTS__
#define __HUD_OBJECTS__

enum HudObjects
{
	HEALTH_TEXT,
	HEALTH_VALUE,
	RED_FIVE_HEALTH_TEXT,
	RED_FIVE_HEALTH_VALUE,
	TIE_FIGHTERS_TEXT,
	TIE_FIGHTERS_VALUE,
	CHEAT_TEXT,
	HUD_OBJECTS_COUNT
};

#endif
