#ifndef __MODELS_ENUM__
#define __MODELS_ENUM__

enum PtModelsEnum
{
	FALCON_MODEL,
	TIE_FIGHTER_MODEL,
	SPHERE_MODEL,
	CUBE_MODEL,
	FLOOR_MODEL,
	STAR_DESTROYER_MODEL,
	PYRAMID_MODEL,
	RING_MODEL,
	PT_MODEL_COUNT
};

#endif