#ifndef __OBJECTS_ENUM__
#define __OBJECTS_ENUM__

enum PtObjectsEnum
{
	MILLENNIUM_FALCON,
	DEATH_STAR,
	STAR_DESTROYER,
	MILLENNIUM_FALCON_BULLET,
	TIE_FIGHTER_BULLET,
	TIE_FIGHTER,
	PLANET,
	SHUTTLE,
	RING,
	PT_OBJECT_COUNT
};

#endif