#ifndef __PT_MATERIALS__
#define __PT_MATERIALS__

enum PtMaterialsEnum
{
	FALCON_MATERIAL,
	TIE_FIGHTER_MATERIAL,
	DEATH_STAR_MATERIAL,
	STAR_DESTROYER_MATERIAL,
	PLANET_MATERIAL,
	FONT_MATERIAL,
	PLASTIC_MATERIAL,
	RED_BEAM_MATERIAL,
	GREEN_BEAM_MATERIAL,
	DOUBLE_EARTH_MATERIAL,
	PYRAMID_MATERIAL,
	RING_MATERIAL,
	PT_MATERIALS_COUNT
};

#endif
