#ifndef __TEXTURES_ENUM__
#define __TEXTURES_ENUM__

enum PtTexturesEnum
{
	FALCON_TEXTURE_WHITE,
	FALCON_TEXTURE_BLACK,
	TIE_FIGHTER_TEXTURE,
	TEDDY_TEXTURE,
	PLANET_TEXTURE,
	COW_TEXTURE,
	FONT_TEXTURE,
	EARTH_GLOSS_TEXTURE,
	DEATH_STAR_TEXTURE,
	RED_BEAM_TEXTURE,
	GREEN_BEAM_TEXTURE,
	PT_TEXTURE_COUNT
};

#endif